services:
  fake-gcs-server:
    image: fsouza/fake-gcs-server
    container_name: fake-gcs-server
    ports:
      - "4443:4443"
    # http://localhost:4443/my-bucket/my-object.txt
    command: >
      -scheme http
      -public-host localhost:4443
      -port 4443
    volumes:
      - ./.docker-data:/data
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./.docker-data/postgres:/var/lib/postgresql/data
